version: '3.5'
services:
    nginx:
        container_name: nginx
        image: jwilder/nginx-proxy
        restart: always
        networks: 
            - nginx_network
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./conf/vhost.d:/etc/nginx/vhost.d:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - ./conf/htpasswd:/etc/nginx/htpasswd 
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
        volumes:
            - ./conf/vhost.d:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - nginx
        environment: 
            DEFAULT_EMAIL: vincentgillibert@gmail.com
            NGINX_PROXY_CONTAINER: nginx

volumes:
    certs:
    html:

networks:
    nginx_network:
        name: nginx_network